---
site_name: "MyPackage"
site_description: "MyPackage"
site_url: https://my_repo.github.io/my_package/
repo_name: my_repo/my_package
repo_url: https://github.com/my_repo/my_package.git
edit_uri_template: 'blob/main/docs/{path}'
copyright: "Copyright &copy; 2024 MyRepo"
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: custom-light
      accent: blue
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: custom-dark
      accent: blue
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    # - announce.dismiss
    # - content.action.edit
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    # - navigation.tabs
    - navigation.top
    - navigation.tracking
    - toc.follow
  icon:
    repo: material/git
  logo: static/images/logo.svg
  favicon: static/favicon.ico
  include_sidebar: false

markdown_extensions:
  - toc:
      permalink: true
      baselevel: 2
  - markdown.extensions.codehilite:
      guess_lang: false
  - admonition
  - codehilite
  - extra
  - mdx_truly_sane_lists
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          # yamllint disable
          format: !!python/name:pymdownx.superfences.fence_code_format ''
          # yamllint enable
  - pymdownx.tabbed:
      alternate_style: true
  - mdx_include:
      base_path: docs

extra_css:
  - static/css/main.css

plugins:
  - search:
      lang: en
  - minify_html
  - macros
  - autorefs
  - privacy
  - mkdocstrings:
      enabled: true
      default_handler: python
      handlers:
        python:
          selection:
            new_path_syntax: true
          paths: [.]
          options:
            filters:
              - "!^_"
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            ignore_init_summary: true
            merge_init_into_class: true
            docstring_style: numpy
            show_submodules: true
            show_root_heading: false
            show_signature_annotations: true
            signature_crossrefs: true
            show_source: true
            group_by_category: false
            show_category_heading: true

nav:
  - MyPackage: index.md
  - Reference:
      - Main: main.md
      - Development: development.md
